#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")" && pwd)"
cd "${SCRIPT_DIR}/.."

xcrun simctl boot "iPhone 17 Pro Max"
open -a Simulator
APP_PATH=".buildIos/Build/Products/Debug-iphonesimulator/Silveran Reader.app"
APP_BUNDLE_ID="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$APP_PATH/Info.plist")"
xcrun simctl install booted "$APP_PATH"
xcrun simctl launch booted "$APP_BUNDLE_ID"
