#!/usr/bin/env bash

SUBSYSTEM="${SILVERAN_LOG_SUBSYSTEM:-$(xcodebuild -project Silveran.xcodeproj -scheme 'Silveran Reader (macOS)' -showBuildSettings 2>/dev/null | awk -F ' = ' '$1 ~ /PRODUCT_BUNDLE_IDENTIFIER/ { print $2; exit }')}"
log stream --style=compact --level=debug --predicate "subsystem == \"$SUBSYSTEM\""
